version: '3'
services:
    database:
        build: .
        environment:
            - MONGO_INITDB_DATABASE=sprach-welt
            - MONGO_INITDB_ROOT_USERNAME=givanx
            - MONGO_INITDB_ROOT_PASSWORD=root
            - ABCDEF=${PWD}
        volumes:
            - /sprach-welt/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongo.js
        ports:
            - '27017-27019:27017-27019'